language: cpp
sudo: false


# don't create redundant code coverage reports
# - AUTOTOOLS=yes COVERAGE=yes BUILD=static
# - AUTOTOOLS=no COVERAGE=yes BUILD=shared
# - AUTOTOOLS=no COVERAGE=no BUILD=static

# further speed up day by day travis-ci builds
# re-enable this if you change the makefiles
# this will still catch all coding errors!
# - AUTOTOOLS=yes COVERAGE=no BUILD=static

# currenty there are various issues when
# built with coverage, clang and autotools
# - AUTOTOOLS=yes COVERAGE=yes BUILD=shared

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "TpS3uet31wPj8l5yjKFMKNHOIHp1Z0W601mCyToSn1+Rp3c6TQAT8kxRmIqp7Etfq7vX+M+KLyEyJZhq0aqmcnov+jm7zvPjNTAV8VrnDL7XdE5cxwqXsxPKCpEnHOAvuCRP0bDYfcK4ds+SP+zIrlFNb83rb+JENHcnDUza5LE="

matrix:
  include :
    - os: linux
      compiler: gcc
      env: AUTOTOOLS=no COVERAGE=yes BUILD=static
    - os: linux
      compiler: g++-5
      env: AUTOTOOLS=yes COVERAGE=no BUILD=shared
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - os: linux
      compiler: clang++-3.7
      env: AUTOTOOLS=no COVERAGE=yes BUILD=static
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
        coverity_scan:
          project:
            name: "sass/libsass"
          build_command_prepend: "<Your build preprocessing command here>"
          build_command: ./script/ci-build-libsass
          branch_pattern: coverity_scan
    - os: linux
      compiler: clang
      env: AUTOTOOLS=yes COVERAGE=no BUILD=shared
    - os: osx
      compiler: clang
      env: AUTOTOOLS=no COVERAGE=no BUILD=shared
    - os: osx
      compiler: clang
      env: AUTOTOOLS=no COVERAGE=yes BUILD=static
    - os: osx
      compiler: clang
      env: AUTOTOOLS=yes COVERAGE=no BUILD=shared

script:
  - ./script/ci-build-libsass
  - ./script/ci-build-plugin math
  - ./script/ci-build-plugin glob
  - ./script/ci-build-plugin digest
  - ./script/ci-build-plugin tests
before_install: ./script/ci-install-deps
install: ./script/ci-install-compiler
after_success: ./script/ci-report-coverage
